language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - python -m pip install --upgrade pip setuptools wheel virtualenv
  - pip install tox tox-travis
  #- pip install -r requirements_test.txt

script:
  #- check-manifest
  - tox

# Run code coverage
after_success: codecov
